services:
  mongo-users:
    image: mongo:7.0
    container_name: mongo-users
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-adminpassword}
      MONGO_INITDB_DATABASE: ${AUTHENTICATION_DATABASE:-ieg-auth-ms}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always

  elasticsearch:
    image: elasticsearch:9.1.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    restart: always

  users-service:
    build:
      context: ./users-service
    container_name: users-service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-users
      - redis
      - elasticsearch
    volumes:
      - ./uploads/profile-pictures:/app/uploads/profile-pictures

  posts-service:
    build:
      context: ./posts-service
    container_name: posts-service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-users
      - redis
      - elasticsearch
    volumes:
      - ./uploads/posts-file:/app/uploads/posts-file
  notifications-service:
    build:
      context: ./notifications-service
    container_name: notifications-service
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo-users
      - redis
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - notifications-service
      - users-service
      - posts-service
      - redis
      - elasticsearch

volumes:
  mongo-data:
