services:
  mongo-users:
    image: mongo:7.0
    container_name: mongo-users
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-adminpassword}
      MONGO_INITDB_DATABASE: ${AUTHENTICATION_DATABASE:-ieg-auth-ms}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  users-service:
    build:
      context: ./users-service
    container_name: users-service
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo-users
      - redis
    volumes:
      - ./uploads/profile-pictures:/app/uploads/profile-pictures

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - users-service
      - redis

volumes:
  mongo-data:
