FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN mkdir -p /app/uploads/profile-pictures && \
    chown -R node:node /app/uploads && \
    chmod -R 755 /app/uploads

ENV NODE_ENV=dev

RUN npm run build

USER node

CMD ["npm", "start"]
