FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

RUN mkdir -p /app/uploads/posts-file && \
    chown -R node:node /app/uploads && \
    chmod -R 755 /app/uploads

USER node

CMD ["node", "dist/server.js"]
